export const DEVNET_SECURE_TOKEN_PACKAGE_ID =
  process.env.NEXT_PUBLIC_DEVNET_SECURE_TOKEN_PACKAGE_ID;

export const DEVNET_TOKEN_OBJECT_ID =
  process.env.NEXT_PUBLIC_DEVNET_TOKEN_OBJECT_ID;

export const TESTNET_SECURE_TOKEN_PACKAGE_ID =
  process.env.NEXT_PUBLIC_TESTNET_SECURE_TOKEN_PACKAGE_ID;
export const TESTNET_TOKEN_OBJECT_ID =
  process.env.NEXT_PUBLIC_TESTNET_TOKEN_OBJECT_ID;

export const MAINNET_SECURE_TOKEN_PACKAGE_ID =
  process.env.NEXT_PUBLIC_MAINNET_SECURE_TOKEN_PACKAGE_ID;
export const MAINNET__TOKEN_OBJECT_ID =
  process.env.NEXT_PUBLIC_MAINNET_TOKEN_OBJECT_ID;
export const MODULE_NAME = process.env.NEXT_PUBLIC_MODULE_NAME;
export const GAS_BUDGET = Number(process.env.NEXT_PUBLIC_GAS_BUDGET);
